// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyzjpbqedradqnckaipx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5empwYnFlZHJhZHFuY2thaXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTE5NDEsImV4cCI6MjA2NjE4Nzk0MX0.CxrFDvd3uwduAYGBqLKNJ4aEXVRjM22_ro6fplKB3yY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);